[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
]
