"""add project user ownership

Revision ID: c6b2cef9f70b
Revises: e965e4c288b7
Create Date: 2026-09-01 20:58:26.810404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b2cef9f70b'
down_revision: Union[str, Sequence[str], None] = 'e965e4c288b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    connection = op.get_bind()

    # The column was already added before SQLite failed
    # while trying to add the foreign key.
    connection.execute(
        sa.text(
            """
            UPDATE projects
            SET user_id = (
                SELECT id
                FROM users
                ORDER BY id
                LIMIT 1
            )
            WHERE user_id IS NULL
            """
        )
    )

    with op.batch_alter_table("projects") as batch_op:
        batch_op.create_foreign_key(
            "fk_projects_user_id",
            "users",
            ["user_id"],
            ["id"]
        )

        batch_op.alter_column(
            "user_id",
            existing_type=sa.Integer(),
            nullable=False
        )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
